
<StatusBar>:
    msg_label: _msg_label
    orientation: 'horizontal'
    Label:
        text: '[b][color=3333ff]Total Figures: ' + str(root.counter) + '[/color][/b]'
        markup: True
    Label:
        text: '[b][color=3333ff]Selected Figures: ' + str(root.selected_counter) + '[/color][/b]'
        markup: True
    Label:
        id: _msg_label
        text: '[b][color=3333ff]Kraken started[/color][/b]'
        markup: True
