#:import toolbox toolbox
<ToolButton@ToggleButton>:
    size_hint: None,None
    size: 48,48
    group: 'tool'
    canvas:
        PushMatrix:
        Translate:
            xy: self.x,self.y
    canvas.after:
        PopMatrix:

<ToolBox@GridLayout>:
    cols: 2
    padding: 2
    tool_circle: _tool_circle
    ToolCircle:
        id: _tool_circle
        canvas:
            Line:
                circle: 24,24,14
