#:import toolbox toolbox
<ToolButton@ToggleButton>:
    size_hint: None,None
    size: 48,48
    group: 'tool'
    canvas:
        PushMatrix:
        Translate:
            xy: self.x,self.y
    canvas.after:
        PopMatrix:

<ToolBox@GridLayout>:
    cols: 1
    padding: 2
    tool_rectangle: _tool_rectangle
    ToolRectangle:
        id: _tool_rectangle
        canvas:
            Line:
                rectangle: 10,10,28,28
    